
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/mnt/bee1/wiibee/wiiboard.py", line 152, in loop
    self.battery = data[14] * 0.039315 + 0.0907875 
IndexError: index out of range
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/mnt/bee1/wiibee/wiiboard.py", line 152, in loop
    self.battery = data[14] * 0.039315 + 0.0907875 
IndexError: index out of range
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/mnt/bee1/wiibee/wiiboard.py", line 152, in loop
    self.battery = data[14] * 0.039315 + 0.0907875 
IndexError: index out of range
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/mnt/bee1/wiibee/wiiboard.py", line 152, in loop
    self.battery = data[14] * 0.039315 + 0.0907875 
IndexError: index out of range
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/mnt/bee1/wiibee/wiiboard.py", line 152, in loop
    self.battery = data[14] * 0.039315 + 0.0907875 
IndexError: index out of range
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/mnt/bee1/wiibee/wiiboard.py", line 152, in loop
    self.battery = data[14] * 0.039315 + 0.0907875 
IndexError: index out of range
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/mnt/bee1/wiibee/wiiboard.py", line 152, in loop
    self.battery = data[14] * 0.039315 + 0.0907875 
IndexError: index out of range
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/mnt/bee1/wiibee/wiiboard.py", line 152, in loop
    self.battery = data[14] * 0.039315 + 0.0907875 
IndexError: index out of range
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/mnt/bee1/wiibee/wiiboard.py", line 152, in loop
    self.battery = data[14] * 0.039315 + 0.0907875 
IndexError: index out of range
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/mnt/bee1/wiibee/wiiboard.py", line 152, in loop
    self.battery = data[14] * 0.039315 + 0.0907875 
IndexError: index out of range
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/mnt/bee1/wiibee/wiiboard.py", line 152, in loop
    self.battery = data[14] * 0.039315 + 0.0907875 
IndexError: index out of range
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/mnt/bee1/wiibee/wiiboard.py", line 152, in loop
    self.battery = data[14] * 0.039315 + 0.0907875 
IndexError: index out of range
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/mnt/bee1/wiibee/wiiboard.py", line 152, in loop
    self.battery = data[14] * 0.039315 + 0.0907875 
IndexError: index out of range
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/mnt/bee1/wiibee/wiiboard.py", line 152, in loop
    self.battery = data[14] * 0.039315 + 0.0907875 
IndexError: index out of range
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/mnt/bee1/wiibee/wiiboard.py", line 152, in loop
    self.battery = data[14] * 0.039315 + 0.0907875 
IndexError: index out of range
/mnt/bee1/wiibee/autorun.sh: line 58:   662 Killed                  echo -e "\xA0\x01\x01\xA2" > /dev/rfcomm0
[2022-03-06 15:01:19,822][wiiboard][ERROR] Could not connect to 00:1E:35:FD:11:FC : [Errno 112] Host is down
